name: minipat
version: 0.1.0

github: ejconlon/minipat
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: A mini pattern language extracted from Tidal
description: Please see the README on GitHub at <https://github.com/ejconlon/minipat#readme>
tested-with: GHC == 9.6.3

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5
- bowtie >= 0.3 && < 0.4
- containers >= 0.6 && < 0.7
- heaps >= 0.4 && < 0.5
- looksee >= 0.5 && < 0.6
- mtl >= 2.3 && < 2.4
- nanotime >= 0.3 && < 0.4
- nonempty-containers >= 0.3 && < 0.4
- prettyprinter >= 1.7 && < 1.8
- text >= 2.0 && < 2.1
- transformers >= 0.6 && < 0.7

library:
  source-dirs: src

tests:
  minipat-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minipat
    - daytripper >= 0.3 && < 0.4
    - tasty >= 1.4 && < 1.5
    - tasty-hunit >= 0.10 && < 0.11
