resolver: lts-23.0

ghc-options:
  "$everything": -haddock

packages:
- minipat
- minipat-live
- minipat-dirt
- minipat-midi
- minipat-rns

extra-deps:
- bowtie-0.4.0
- dahdit-0.7.0
- dahdit-network-0.7.0
- dahdit-midi-0.7.0
- data-sword-0.2.0.3
- daytripper-1.0.0
- libremidi-0.4.0
- little-logger-3.0.1
- looksee-0.8.0
- nanotime-0.3.2
- prop-unit-1.0.1
