resolver: lts-23.0

# TODO Bump package versions
allow-newer: true

ghc-options:
  "$everything": -haddock

packages:
- minipat
- minipat-live
- minipat-dirt
- minipat-midi
- minipat-rns

extra-deps:
- bowtie-0.4.0
- dahdit-0.5.1
- dahdit-network-0.5.2
- dahdit-midi-0.5.5
- data-sword-0.2.0.3
- daytripper-0.3.1
- little-logger-1.0.2
- falsify-0.2.0@r1
- looksee-0.6.0
- nanotime-0.3.2
- git: git@github.com:ejconlon/libremidi-haskell.git
  commit: cdec4720257bcd0a22e1156e87bf361a7be70ce7
  subdirs:
  - libremidi
