resolver: lts-22.33

ghc-options:
  "$everything": -haddock

packages:
- minipat
- minipat-live
- minipat-dirt
- minipat-midi

extra-deps:
- bowtie-0.4.0
- dahdit-0.5.1
- dahdit-network-0.5.2
- dahdit-midi-0.5.5
- data-sword-0.2.0.3
- daytripper-0.3.1
- little-logger-1.0.2
- falsify-0.2.0@r1
- looksee-0.6.0
- nanotime-0.3.2
- git: git@github.com:ejconlon/libremidi-haskell.git
  commit: 64fe2ad4720f014eb55f3a1d2a3e63313d2debce
  subdirs:
  - libremidi
