name: minipat-midi
version: 0.1.0

github: ejconlon/minipat
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: MIDI backend for minipat
description: Please see the README on GitHub at <https://github.com/ejconlon/minipat#readme>
tested-with: GHC == 9.6.4

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5
- containers >= 0.6 && < 0.7
- dahdit >= 0.5.1 && < 0.6
- dahdit-midi >= 0.5.5 && < 0.6
- heaps >= 0.4 && < 0.5
- minipat >= 0.1 && < 0.2
- minipat-live >= 0.1 && < 0.2
- nanotime >= 0.3.2 && < 0.4
- resourcet >= 1.3 && < 1.4
- RtMidi >= 0.8 && < 1.0
- stm >= 2.5 && < 2.6
- text >= 2.0 && < 2.1
- vector >= 0.13 && < 0.14

library:
  source-dirs: src

