name: minipat-dirt
version: 0.1.0

github: ejconlon/minipat
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: SuperDirt integration for minipat
description: Please see the README on GitHub at <https://github.com/ejconlon/minipat#readme>
tested-with: GHC == 9.6.4

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5
- async >= 2.2 && < 2.3
- containers >= 0.6 && < 0.7
- dahdit-midi >= 0.5.5 && < 0.6
- dahdit-network >= 0.5.2 && < 0.6
- minipat >= 0.1 && < 0.2
- minipat-live >= 0.1 && < 0.2
- nanotime >= 0.3.2 && < 0.4
- network >= 3.1 && < 3.2
- text >= 2.0 && < 2.1
- stm >= 2.5 && < 2.6

library:
  source-dirs: src

