name: minipat-rns
version: 0.1.0

github: ejconlon/minipat
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: Renoise utils
description: Please see the README on GitHub at <https://github.com/ejconlon/minipat#readme>
tested-with: GHC == 9.6.4

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5
- async >= 2.2 && < 2.3
- bytestring >= 0.11 && < 0.13
- containers >= 0.6 && < 0.7
- dahdit >= 0.7 && < 0.8
- dahdit-midi >= 0.7 && < 0.8
- data-default >= 0.7 && < 0.8
- heaps >= 0.4 && < 0.5
- minipat >= 0.1 && < 0.2
- minipat-live >= 0.1 && < 0.2
- nanotime >= 0.3.2 && < 0.4
- resourcet >= 1.3 && < 1.4
- stm >= 2.5 && < 2.6
- text >= 2.0 && < 2.2
- vector >= 0.13 && < 0.14
- libremidi >= 0.4 && < 0.5
- mtl >= 2.3.1 && < 2.4
- exceptions >= 0.10.7 && < 0.11
- prettyprinter >= 1.7.1 && < 1.8

library:
  source-dirs: src
