name: minipat-live
version: 0.1.0

github: ejconlon/minipat
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: Live coding for Minipat
description: Please see the README on GitHub at <https://github.com/ejconlon/minipat#readme>
tested-with: GHC == 9.6.4

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5
- async >= 2.2 && < 2.3
- containers >= 0.6 && < 0.7
- dahdit-midi >= 0.5.5 && < 0.6
- data-default >= 0.7 && < 0.8
- exceptions >= 0.10 && < 0.11
- heaps >= 0.4 && < 0.5
- little-logger >= 1.0 && < 1.1
- looksee >= 0.5.2 && < 0.6
- minipat >= 0.1 && < 0.2
- mtl >= 2.3 && < 2.4
- nanotime >= 0.3.2 && < 0.4
- prettyprinter >= 1.7 && < 1.8
- resourcet >= 1.3 && < 1.4
- stm >= 2.5 && < 2.6
- text >= 2.0 && < 2.1

library:
  source-dirs: src

tests:
  minipat-live-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minipat-live
    - tasty >= 1.4 && < 1.5
    - tasty-hunit >= 0.10 && < 0.11
